import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unnecessary_brace_in_string_interps

//WARNING: This file is automatically generated. DO NOT EDIT, all your changes would be lost.

typedef LocaleChangeCallback = void Function(Locale locale);

class I18n implements WidgetsLocalizations {
  const I18n();
  static Locale _locale;
  static bool _shouldReload = false;

  static set locale(Locale newLocale) {
    _shouldReload = true;
    I18n._locale = newLocale;
  }

  static const GeneratedLocalizationsDelegate delegate = GeneratedLocalizationsDelegate();

  /// function to be invoked when changing the language
  static LocaleChangeCallback onLocaleChanged;

  static I18n of(BuildContext context) =>
    Localizations.of<I18n>(context, WidgetsLocalizations);

  @override
  TextDirection get textDirection => TextDirection.ltr;

  /// "你好 ${name}"
  String greetTo(String name) => "你好 ${name}";
  /// "登入"
  String get login => "登入";
  /// "登出"
  String get loginout => "登出";
  /// "中文"
  String get language => "中文";
  /// "切换语言"
  String get lang => "切换语言";
  /// "首页"
  String get home => "首页";
  /// "兑换"
  String get exchange => "兑换";
  /// "市场"
  String get market => "市场";
  /// "我的"
  String get mine => "我的";
  /// "我的背包"
  String get mypackage => "我的背包";
  /// "充值"
  String get recharge => "充值";
  /// "提现"
  String get withdraw => "提现";
  /// "提现地址："
  String get withdrawaddress => "提现地址：";
  /// "提现数量："
  String get withdrawnum => "提现数量：";
  /// "提现需知："
  String get withdrawrule => "提现需知：";
  /// "提现成功"
  String get withdrawsuccess => "提现成功";
  /// "到账数量："
  String get arrivalquantity => "到账数量：";
  /// "团队"
  String get team => "团队";
  /// "日收益"
  String get dayincome => "日收益";
  /// "我的团队"
  String get myteam => "我的团队";
  /// "我的收益"
  String get myearn => "我的收益";
  /// "邀请好友"
  String get invite => "邀请好友";
  /// "申诉"
  String get shensu => "申诉";
  /// "买家未付款，交易取消"
  String get buynotpay => "买家未付款，交易取消";
  /// "买家已付款，确认放币"
  String get buypaiad => "买家已付款，确认放币";
  /// "我已付款，卖家未放币"
  String get sellnotpaycoin => "我已付款，卖家未放币";
  /// "自助解封"
  String get autoaccount => "自助解封";
  /// "您的账户交易规范，无不良记录，请继续保持！"
  String get accountright => "您的账户交易规范，无不良记录，请继续保持！";
  /// "解封账号"
  String get unlockaccount => "解封账号";
  /// "委托中的"
  String get weituo => "委托中的";
  /// "密码"
  String get password => "密码";
  /// "请填写证件上的真实姓名"
  String get pleaseinputname => "请填写证件上的真实姓名";
  /// "请填写证件号"
  String get pleaseinputid => "请填写证件号";
  /// "请输入您绑定银行卡的手机号码"
  String get pleaseinputbanknumber => "请输入您绑定银行卡的手机号码";
  /// "姓名"
  String get name => "姓名";
  /// "证件类型"
  String get idtype => "证件类型";
  /// "证件号"
  String get idnumber => "证件号";
  /// "驾驶证"
  String get iddrive => "驾驶证";
  /// "护照"
  String get idprotect => "护照";
  /// "身份证"
  String get idcard => "身份证";
  /// "手机"
  String get phone => "手机";
  /// "邮箱"
  String get email => "邮箱";
  /// "恭喜获得"
  String get congratulations => "恭喜获得";
  /// "请输入手机号码"
  String get pleaseinputphone => "请输入手机号码";
  /// "请输入邮箱"
  String get pleaseinputemail => "请输入邮箱";
  /// "请输入密码"
  String get pleaseinputpwd => "请输入密码";
  /// "输入交易密码"
  String get pleasetxpassword => "输入交易密码";
  /// "请输入验证码"
  String get verificationcode => "请输入验证码";
  /// "请输入新密码"
  String get pleaseinputnewpwd => "请输入新密码";
  /// "请确认新密码"
  String get confirminputnewpwd => "请确认新密码";
  /// "确认并前往登入"
  String get confirmlogin => "确认并前往登入";
  /// "获取验证码"
  String get getcoude => "获取验证码";
  /// "重新获取"
  String get reacquire => "重新获取";
  /// "兑换成功"
  String get exchagesuccess => "兑换成功";
  /// "设置"
  String get setting => "设置";
  /// "安全中心"
  String get safecenter => "安全中心";
  /// "帮助反馈"
  String get feedback => "帮助反馈";
  /// "关于"
  String get about => "关于";
  /// "数量"
  String get number => "数量";
  /// "日期"
  String get date => "日期";
  /// "时间"
  String get time => "时间";
  /// "总计"
  String get total => "总计";
  /// "完成"
  String get finish => "完成";
  /// "实名认证"
  String get verified => "实名认证";
  /// "目前绑定"
  String get currentbinding => "目前绑定";
  /// "登入密码"
  String get loginpwd => "登入密码";
  /// "交易密码"
  String get txpassword => "交易密码";
  /// "保存"
  String get save => "保存";
  /// "金铲子"
  String get shovel_gold => "金铲子";
  /// "银铲子"
  String get shovel_sliver => "银铲子";
  /// "铜铲子"
  String get shovel_iron => "铜铲子";
  /// "新手"
  String get newer => "新手";
  /// "前往背包查看"
  String get gotopackage => "前往背包查看";
  /// "邀请记录"
  String get inviterecord => "邀请记录";
  /// "可用资产"
  String get availablebalance => "可用资产";
  /// "可用资产"
  String get assetaccount => "可用资产";
  /// "分享奖励"
  String get teamgroupshare => "分享奖励";
  /// "领导奖金"
  String get teamgroupleader => "领导奖金";
  /// "直推奖"
  String get teamgrouppush => "直推奖";
  /// "输出"
  String get output => "输出";
  /// "预估"
  String get estimate => "预估";
  /// "昨日团队收益价值"
  String get lasetteamvalue => "昨日团队收益价值";
  /// "总价值收益"
  String get totalteamvalue => "总价值收益";
  /// "建立自己团队的矿场\n参与MIGO矿池分红"
  String get totalnotice => "建立自己团队的矿场\n参与MIGO矿池分红";
  /// "立即参与"
  String get teamjoin => "立即参与";
  /// "小区日静态产出"
  String get teamstaticvalue => "小区日静态产出";
  /// "余额"
  String get balance => "余额";
  /// "选择币种"
  String get choosecoin => "选择币种";
  /// "价格"
  String get price => "价格";
  /// "手续费减免"
  String get feereduction => "手续费减免";
  /// "手续费"
  String get feereduction2 => "手续费";
  /// "当前${level}级别"
  String currlevel(String level) => "当前${level}级别";
  /// "下一级${level}级别"
  String nextlevel(String level) => "下一级${level}级别";
  /// "目前购买配套"
  String get currbuy => "目前购买配套";
  /// "立即兑换"
  String get redeemnow => "立即兑换";
  /// "确认兑换"
  String get confirmexchange => "确认兑换";
  /// "供应量"
  String get supply => "供应量";
  /// "最少获得"
  String get leastget => "最少获得";
  /// "价格滑点"
  String get priceslippage => "价格滑点";
  /// "手续费"
  String get handlingfee => "手续费";
  /// "购买 ${e} 配套"
  String buy(String e) => "购买 ${e} 配套";
  /// "用户名或密码错误"
  String get erroraccount => "用户名或密码错误";
  /// "忘记密码?"
  String get forgetpwd => "忘记密码?";
  /// "注册新账号"
  String get register => "注册新账号";
  /// "下一步"
  String get next => "下一步";
  /// "确认"
  String get sure => "确认";
  /// "取消"
  String get cancel => "取消";
  /// "请问确定要登出吗？"
  String get canyouexit => "请问确定要登出吗？";
  /// "扫描二维码进行充值"
  String get scanqrtorecharge => "扫描二维码进行充值";
  /// "充值地址（复制地址如下)"
  String get copyaddress => "充值地址（复制地址如下)";
  /// "小时"
  String get hour => "小时";
  /// "APP升级提示"
  String get upnotice => "APP升级提示";
  /// "再按一次退出"
  String get againexit => "再按一次退出";
  /// "1. 最小充值金额: ${e} USDT，小于这个金额将不会上账且无法退回。"
  String notice1(String e) => "1. 最小充值金额: ${e} USDT，小于这个金额将不会上账且无法退回。";
  /// "1. 此地址只接受${e}资产，发送其他币种到此地址将不可找回。"
  String notice2(String e) => "1. 此地址只接受${e}资产，发送其他币种到此地址将不可找回。";
  /// "2. 默认充值至钱包余额。"
  String get notice3 => "2. 默认充值至钱包余额。";
  /// "3. 您的充值地址不会经常改变，可以重复充值；如有更改，我们会尽量通过网站公告或邮件通知您。"
  String get notice4 => "3. 您的充值地址不会经常改变，可以重复充值；如有更改，我们会尽量通过网站公告或邮件通知您。";
  /// "请输入或长按粘贴"
  String get pleaseinputorcopy => "请输入或长按粘贴";
  /// "请输入数量"
  String get pleaseinputonumber => "请输入数量";
  /// "可提数量："
  String get availableamount => "可提数量：";
  /// "实际到账："
  String get actualarrival => "实际到账：";
  /// "赚取"
  String get homeearn => "赚取";
  /// "抵押"
  String get mortgage => "抵押";
  /// "需支付"
  String get homepay => "需支付";
  /// "日产量"
  String get dailyoutput => "日产量";
  /// "挖矿周期"
  String get miningcycle => "挖矿周期";
  /// "挖矿量"
  String get miningamount => "挖矿量";
  /// "添加其他方式"
  String get addother => "添加其他方式";
  /// "请添加支付方式"
  String get addpaymethod => "请添加支付方式";
  /// "请选择支付方式"
  String get pleaseaddpay => "请选择支付方式";
  /// "矿池日产量"
  String get miningoutput => "矿池日产量";
  /// "矿池总产量"
  String get miningtotaloutput => "矿池总产量";
  /// "获得"
  String get obtain => "获得";
  /// "立即挖矿"
  String get minenow => "立即挖矿";
  /// "已使用"
  String get homeused => "已使用";
  /// "支付记录"
  String get miningpaymentrecord => "支付记录";
  /// "收益记录"
  String get miningrevenuerecord => "收益记录";
  /// "团队收益记录"
  String get teamearnrecord => "团队收益记录";
  /// "支付"
  String get pay => "支付";
  /// "分享奖励"
  String get sharerewards => "分享奖励";
  /// "目前称号"
  String get currtitle => "目前称号";
  /// "小区累计质押挖矿"
  String get cumulativepledgedmining => "小区累计质押挖矿";
  /// "达标等级"
  String get compliancelevel => "达标等级";
  /// "见点奖励"
  String get seePoint => "见点奖励";
  /// "使用中铲子"
  String get shovelinuse => "使用中铲子";
  /// "天"
  String get day => "天";
  /// "已认证"
  String get inviteverified => "已认证";
  /// "未认证"
  String get notinviteverified => "未认证";
  /// "全部"
  String get all => "全部";
  /// "代"
  String get generation => "代";
  /// "每个有效用户"
  String get everyactiveuser => "每个有效用户";
  /// "奖励"
  String get reward => "奖励";
  /// "享受"
  String get enjoy => "享受";
  /// "当前等级"
  String get currentlevel => "当前等级";
  /// "矿池分红"
  String get minedividends => "矿池分红";
  /// "我的小区"
  String get mycommunity => "我的小区";
  /// "今日完成认证人数"
  String get numberpeople => "今日完成认证人数";
  /// "累计完成认证人数"
  String get totalnumberpeople => "累计完成认证人数";
  /// "设置新密码"
  String get resetpwd => "设置新密码";
  /// "${sender}"
  String space(String sender) => "${sender}";
  /// "共"
  String get teamleadertotal => "共";
  /// "团队人数"
  String get teamnumber => "团队人数";
  /// "昨日团队收益"
  String get teamperformance => "昨日团队收益";
  /// "大区挖矿金额"
  String get dynamicincome => "大区挖矿金额";
  /// "直推奖"
  String get directPushAward => "直推奖";
  /// "达标领导奖励"
  String get aimreward => "达标领导奖励";
  /// "我的面值"
  String get denomination => "我的面值";
  /// "更新资产"
  String get coinupdate => "更新资产";
  /// "历史记录"
  String get history => "历史记录";
  /// "温馨提示"
  String get notice => "温馨提示";
  /// "上传证件照"
  String get uploadid => "上传证件照";
  /// "手持证件照的正面"
  String get idfront => "手持证件照的正面";
  /// "手持证件照的反面"
  String get idback => "手持证件照的反面";
  /// "提现地址不合法，请重新输入"
  String get noticenotaddress => "提现地址不合法，请重新输入";
  /// "拍摄"
  String get takephoto => "拍摄";
  /// "从相册选择"
  String get album => "从相册选择";
  /// "提交"
  String get submit => "提交";
  /// "更改绑定"
  String get changebind => "更改绑定";
  /// "当前绑定"
  String get currbind => "当前绑定";
  /// "绑定规则：手机号及邮箱选择一个绑定即可"
  String get bindrule => "绑定规则：手机号及邮箱选择一个绑定即可";
  /// "转券"
  String get reeltitle => "转券";
  /// "转券"
  String get reelaction => "转券";
  /// "转赠于用户："
  String get coupontouser => "转赠于用户：";
  /// "转赠数量："
  String get coupontousercount => "转赠数量：";
  /// "验证用户"
  String get reelverified => "验证用户";
  /// "请先验证用户"
  String get pleasereelverified => "请先验证用户";
  /// "最大${e}"
  String reelmaxcount(String e) => "最大${e}";
  /// "再加一个"
  String get addone => "再加一个";
  /// "抱歉，你输入的用户ID还没注册，无法转赠"
  String get reelerror => "抱歉，你输入的用户ID还没注册，无法转赠";
  /// "恭喜,该ID为已注册ID"
  String get reelsuccess => "恭喜,该ID为已注册ID";
  /// "当前总生产率"
  String get currtotalproduce => "当前总生产率";
  /// "背包容量"
  String get packagesize => "背包容量";
  /// "今日预估获得"
  String get todaypreget => "今日预估获得";
  /// "累计产出"
  String get totalgetmigos => "累计产出";
  /// "规格"
  String get specification => "规格";
  /// "耐久度"
  String get durability => "耐久度";
  /// "生产量"
  String get production => "生产量";
  /// "体积"
  String get volume => "体积";
  /// "使用"
  String get use => "使用";
  /// "请问确定要使用此道具吗?"
  String get usernotice => "请问确定要使用此道具吗?";
  /// "1. 证件类型:身份证、护照或驾照。\n2. 必须看清证件信息和脸，需要手持证件拍摄。\n3. 证件文档不可超过500kb。\n4. 照片内容真实有效，不得做任何修改。\n5. 上传文档格式为pdf、jpg、 jpeg和png。"
  String get uploadnotice => "1. 证件类型:身份证、护照或驾照。\n2. 必须看清证件信息和脸，需要手持证件拍摄。\n3. 证件文档不可超过500kb。\n4. 照片内容真实有效，不得做任何修改。\n5. 上传文档格式为pdf、jpg、 jpeg和png。";
  /// "姓名、证件号首次提交后无法更改，为避免填写虚假信息导致充值、提现无法审核通过，请您慎重填写真实信息。"
  String get authnotice => "姓名、证件号首次提交后无法更改，为避免填写虚假信息导致充值、提现无法审核通过，请您慎重填写真实信息。";
  /// "我的邀请码: "
  String get myinvitecode => "我的邀请码: ";
  /// "邀请10个好友并完成实名认证 \n 即可获得一个盲盒"
  String get myinvitecodenotice => "邀请10个好友并完成实名认证 \n 即可获得一个盲盒";
  /// "邀请链接"
  String get invitelink => "邀请链接";
  /// "保存海报"
  String get saveimage => "保存海报";
  /// "人"
  String get peopleintotal => "人";
  /// "操作成功"
  String get success => "操作成功";
  /// "收益记录"
  String get earnrecord => "收益记录";
  /// "1. 提现会扣取部分手续费，以实际到账为主。"
  String get withDrawNotice => "1. 提现会扣取部分手续费，以实际到账为主。";
  /// "用户协议"
  String get settinguserprotocol => "用户协议";
  /// "隐私协议"
  String get settingprotocol => "隐私协议";
  /// "APP版本更新内容"
  String get settingupdate => "APP版本更新内容";
  /// "APP当前版本"
  String get appcurrversion => "APP当前版本";
  /// "好友邀请流程"
  String get feedinvite => "好友邀请流程";
  /// "账号管理事宜"
  String get feedaccount => "账号管理事宜";
  /// "矿场收益解释"
  String get feedmines => "矿场收益解释";
  /// "其他功能使用"
  String get feeduse => "其他功能使用";
  /// "实际支付金额"
  String get realpayamount => "实际支付金额";
  /// "当前购买量"
  String get realpayamount2 => "当前购买量";
  /// "我要发送反馈"
  String get feed => "我要发送反馈";
  /// "撤资删号流程"
  String get feeddel => "撤资删号流程";
  /// "请简要描述您的问题或者意见，以便我们为您提供更好的帮助。"
  String get feennotice => "请简要描述您的问题或者意见，以便我们为您提供更好的帮助。";
  /// "选择文件"
  String get feedchoose => "选择文件";
  /// "请输入内容"
  String get pleaseinput => "请输入内容";
  /// "使用中"
  String get using => "使用中";
  /// "铲子"
  String get shovel => "铲子";
  /// "待成交"
  String get waitbuy => "待成交";
  /// "交易中"
  String get buying => "交易中";
  /// "点击修改支付信息"
  String get modpay => "点击修改支付信息";
  /// "已支付"
  String get paid => "已支付";
  /// "全球矿池分红总额"
  String get mineaddgrade => "全球矿池分红总额";
  /// "今日全球矿池分红"
  String get minetodayaddgrade => "今日全球矿池分红";
  /// "累积全球矿池分红总额"
  String get minetotaladdgrade => "累积全球矿池分红总额";
  /// "起止日期"
  String get startdate => "起止日期";
  /// "分红日期"
  String get getmoneydate => "分红日期";
  /// "团队概况"
  String get teamdetail => "团队概况";
  /// "我的直推"
  String get minepush => "我的直推";
  /// "我的伞下"
  String get mineumbrella => "我的伞下";
  /// "我的直推人数"
  String get minepushanumber => "我的直推人数";
  /// "我的伞下人数"
  String get mineumbrellanumber => "我的伞下人数";
  /// "本周新增质押"
  String get weakaddMEGO => "本周新增质押";
  /// "累计质押"
  String get allmego => "累计质押";
  /// "全球矿池分红"
  String get earthmoney => "全球矿池分红";
  /// "有效用户数"
  String get realuser => "有效用户数";
  /// "银行卡号"
  String get bankNo => "银行卡号";
  /// "请输入正确的银行卡号"
  String get pleasebankNo => "请输入正确的银行卡号";
  /// "请输入单价"
  String get pleaseprice => "请输入单价";
  /// "交易手续费用等级"
  String get selllevel => "交易手续费用等级";
  /// "待认证"
  String get auth0 => "待认证";
  /// "审核中"
  String get auth1 => "审核中";
  /// "审核通过"
  String get auth2 => "审核通过";
  /// "审核拒绝"
  String get auth3 => "审核拒绝";
  /// "中国国内用户"
  String get curruser => "中国国内用户";
  /// "海外地区用户"
  String get otheruser => "海外地区用户";
  /// "充提历史记录"
  String get rechargerecord => "充提历史记录";
  /// "提币记录"
  String get relfectrecord => "提币记录";
  /// "待审核"
  String get coinStatus0 => "待审核";
  /// "转账中"
  String get coinStatus1 => "转账中";
  /// "确认中"
  String get coinStatus2 => "确认中";
  /// "转账成功"
  String get coinStatus3 => "转账成功";
  /// "审批拒绝"
  String get coinStatus4 => "审批拒绝";
  /// "转账失败"
  String get coinStatus5 => "转账失败";
  /// "发送交易中"
  String get coinStatus6 => "发送交易中";
  /// "打包中"
  String get coinStatus7 => "打包中";
  /// "兑换历史"
  String get exchangehistory => "兑换历史";
  /// "充足"
  String get enough => "充足";
  /// "已完成"
  String get alfinish => "已完成";
  /// "暂不支持ERC20"
  String get rechargeNotsupport => "暂不支持ERC20";
  /// "到账数量"
  String get realnum => "到账数量";
  /// "备注"
  String get remark => "备注";
  /// "达标"
  String get arriveAim => "达标";
  /// "已获得"
  String get geted => "已获得";
  /// "充值提现订单"
  String get rechagerecordorder => "充值提现订单";
  /// "暂无奖励"
  String get nomoney => "暂无奖励";
  /// "昨日收益"
  String get yearterdayoutput => "昨日收益";
  /// "请输入6位密码"
  String get pleasesixpwd => "请输入6位密码";
  /// "最小提币${e}"
  String pleasemincoinnumber(String e) => "最小提币${e}";
  /// "请输入数量大于${e}"
  String noticemincoimnumber(String e) => "请输入数量大于${e}";
  /// "请输入6-12位数字字母组合密码"
  String get pleasesixto12pwd => "请输入6-12位数字字母组合密码";
  /// "您已输入密码错误5次,请更换新密码"
  String get pleasereinputnew => "您已输入密码错误5次,请更换新密码";
  /// "检测到您还没设置自己的交易密码，请马上前往设置"
  String get nottxpwd => "检测到您还没设置自己的交易密码，请马上前往设置";
  /// "1）姓名、身份证件号在认证后将无法更改，为避免填写虚假信息导致充值、提现无法审核通过，请慎重填写您的真实信息。\n2）请填写您的绑定该银行卡的手机号。\n3）请您耐心等候，因为审核认证过程需要时间处理。"
  String get threeauthNotice => "1）姓名、身份证件号在认证后将无法更改，为避免填写虚假信息导致充值、提现无法审核通过，请慎重填写您的真实信息。\n2）请填写您的绑定该银行卡的手机号。\n3）请您耐心等候，因为审核认证过程需要时间处理。";
  /// "1）姓名、身份证件号在认证后将无法更改，为避免填写虚假信息导致充值、提现无法审核通过，请慎重填写您的真实信息。\n2）请您在按下一步后手持该证件照拍照，需要清晰地看到您的人脸，证件前后的资料信息。除此之外，你需要另备一小小字条，清晰地写上你自己MIGO里的邀请码，如不符合，客服有权拒绝审核认证。\n3）请您耐心等候，因为审核认证过程需要时间处理。（海外用户会需时更久）"
  String get threeauthNotice2 => "1）姓名、身份证件号在认证后将无法更改，为避免填写虚假信息导致充值、提现无法审核通过，请慎重填写您的真实信息。\n2）请您在按下一步后手持该证件照拍照，需要清晰地看到您的人脸，证件前后的资料信息。除此之外，你需要另备一小小字条，清晰地写上你自己MIGO里的邀请码，如不符合，客服有权拒绝审核认证。\n3）请您耐心等候，因为审核认证过程需要时间处理。（海外用户会需时更久）";
  /// "1. 最小提币量为${e}。\n2. 提现会扣取部分手续费，以实际到账为主。\n3. 实际到账数量会经过一定的审核判断，以每日可提现额度为基准。\n4. 为保障您的资金的安全，当您改变了密码或者其他安全相关的个人信息，我们会对提币进行人工审核"
  String withdrawnoticerule(String e) => "1. 最小提币量为${e}。\n2. 提现会扣取部分手续费，以实际到账为主。\n3. 实际到账数量会经过一定的审核判断，以每日可提现额度为基准。\n4. 为保障您的资金的安全，当您改变了密码或者其他安全相关的个人信息，我们会对提币进行人工审核";
  /// "密码不一致"
  String get notsamepwd => "密码不一致";
  /// "转赠认证券需知："
  String get reealnotice => "转赠认证券需知：";
  /// "1. 最低转赠单位为1。"
  String get reealnotice1 => "1. 最低转赠单位为1。";
  /// "2. 你可以一次性转赠最多五个用户。"
  String get reealnotice2 => "2. 你可以一次性转赠最多五个用户。";
  /// "3. 请先验证您输入的用户ID，确认为已注册用户方能转赠。"
  String get reealnotice3 => "3. 请先验证您输入的用户ID，确认为已注册用户方能转赠。";
  /// "4. 点击右上角的图标可以查看您的认证券转赠记录。"
  String get reealnotice4 => "4. 点击右上角的图标可以查看您的认证券转赠记录。";
  /// "转券记录"
  String get reelrecord => "转券记录";
  /// "实名认证券转赠记录"
  String get reelrecordhead => "实名认证券转赠记录";
  /// "实名认证券"
  String get reelusename => "实名认证券";
  /// "你目前有${e}张可用认证券，确认使用吗？"
  String reelusecontent(String e) => "你目前有${e}张可用认证券，确认使用吗？";
  /// "已消耗一张认证券！请耐心等待认证结果"
  String get reeluserd => "已消耗一张认证券！请耐心等待认证结果";
  /// "您目前没有任何可用认证券，\n请跟您的邀请人或者上级领导获取！"
  String get reelnouse => "您目前没有任何可用认证券，\n请跟您的邀请人或者上级领导获取！";
  /// "请输入手机号或者邮箱"
  String get pleaseinputuserid => "请输入手机号或者邮箱";
  /// "请输入数量: 最低为1"
  String get pleaseinputreelnumber => "请输入数量: 最低为1";
  /// "转赠用户数达到上限"
  String get reelnumbertomax => "转赠用户数达到上限";
  /// "已转券成功"
  String get reelrequestSuccess => "已转券成功";
  /// "当前认证券数量："
  String get reelrequestcurrnumber => "当前认证券数量：";
  /// "无法转券给同个账号"
  String get notsameaccount => "无法转券给同个账号";
  /// "认证券数量不足, 请修改数量"
  String get reelnumbertonotenough => "认证券数量不足, 请修改数量";
  /// "请输入6位数的交易密码"
  String get pleasesixtxpwd => "请输入6位数的交易密码";
  /// "汇率"
  String get huilv => "汇率";
  /// "已转赠"
  String get reelstatus1 => "已转赠";
  /// "此区域还未开放"
  String get notopen => "此区域还未开放";
  /// "质押挖矿总额"
  String get teamminetotal => "质押挖矿总额";
  /// "已加额"
  String get reelstatus2 => "已加额";
  /// "已使用"
  String get reelstatus3 => "已使用";
  /// "已返还"
  String get reelstatus4 => "已返还";
  /// "全球分红"
  String get globlalmoney => "全球分红";
  /// "团队奖励"
  String get teammoney => "团队奖励";
  /// "已转赠"
  String get reeledfinish => "已转赠";
  /// "总区质押挖矿总额"
  String get teamtotaltotal => "总区质押挖矿总额";
  /// "小区质押挖矿总额"
  String get teamtotalmin => "小区质押挖矿总额";
  /// "提示\n请您在12月18号前前往安全中心绑定您的手机号码，否则将无法登录"
  String get cannoteamil => "提示\n请您在12月18号前前往安全中心绑定您的手机号码，否则将无法登录";
  /// "第${e}代"
  String secondegenra(String e) => "第${e}代";
  /// "已实名"
  String get auth => "已实名";
  /// "海外人工认证"
  String get authother => "海外人工认证";
  /// "交易所"
  String get coinexchange => "交易所";
  /// "敬请期待"
  String get notopen2 => "敬请期待";
  /// "即将开放"
  String get notopen3 => "即将开放";
  /// "今日参考价"
  String get extodayprice => "今日参考价";
  /// "今日价格"
  String get extodaypricecny => "今日价格";
  /// "昨日价格"
  String get exyesterdayprice => "昨日价格";
  /// "涨幅"
  String get exupdown => "涨幅";
  /// "今日交易量"
  String get extodaycount => "今日交易量";
  /// "平台累计交易量"
  String get explatformcount => "平台累计交易量";
  /// "可用余额"
  String get exablebanence => "可用余额";
  /// "购买"
  String get exbuy => "购买";
  /// "当前购买列表"
  String get exbuylist => "当前购买列表";
  /// "订单号"
  String get exorderno => "订单号";
  /// "订单数量"
  String get exordernoNum => "订单数量";
  /// "单价"
  String get exsingleprice => "单价";
  /// "预计金额"
  String get expreamount => "预计金额";
  /// "立即出售"
  String get exsellnow => "立即出售";
  /// "已完成"
  String get finished => "已完成";
  /// "发布购买"
  String get expostbuy => "发布购买";
  /// "数额"
  String get exposetnumber => "数额";
  /// "请输入购买数额"
  String get expostplease => "请输入购买数额";
  /// "同步参考价"
  String get expostasync => "同步参考价";
  /// "自定义价格"
  String get expostself => "自定义价格";
  /// "涨价比例"
  String get expostbili => "涨价比例";
  /// "支付方式"
  String get expostpaymethod => "支付方式";
  /// "微信"
  String get paywx => "微信";
  /// "支付宝"
  String get payalipay => "支付宝";
  /// "银行卡"
  String get paybank => "银行卡";
  /// "确认发布"
  String get expostsend => "确认发布";
  /// "总价"
  String get totalprice => "总价";
  /// "成交时间"
  String get subtime => "成交时间";
  /// "待付款"
  String get rnotpay => "待付款";
  /// "待确认"
  String get rnotsure => "待确认";
  /// "已完成"
  String get rfinish => "已完成";
  /// "已撤销"
  String get rnotfinish => "已撤销";
  /// "撤销"
  String get revoke => "撤销";
  /// "交易订单"
  String get rtitle => "交易订单";
  /// "出售"
  String get rsell => "出售";
  /// "确认已支付"
  String get rsurepay => "确认已支付";
  /// "等待对方放币"
  String get rsurepaycoin => "等待对方放币";
  /// "付款信息"
  String get rpayinfo => "付款信息";
  /// "收款方式"
  String get spaysetting => "收款方式";
  /// "购买"
  String get rbuy => "购买";
  /// "我购买的"
  String get rbuytitle => "我购买的";
  /// "我出售的"
  String get rselltitle => "我出售的";
  /// "收款人姓名："
  String get susername => "收款人姓名：";
  /// "请输入收款人姓名"
  String get susernameplease => "请输入收款人姓名";
  /// "例如：支付宝名/银行卡/TRC20钱包持有人名"
  String get snameeg => "例如：支付宝名/银行卡/TRC20钱包持有人名";
  /// "收款账号："
  String get saccount => "收款账号：";
  /// "收款地址："
  String get saccountaddress => "收款地址：";
  /// "请输入收款账户"
  String get saccountplease => "请输入收款账户";
  /// "例如：支付宝手机号/银行卡号/TRC20钱包地址"
  String get saccounteg => "例如：支付宝手机号/银行卡号/TRC20钱包地址";
  /// "开户银行："
  String get bankename => "开户银行：";
  /// "请输入开户银行"
  String get pleasebankname => "请输入开户银行";
  /// "例如：中国建设银行"
  String get bandeg => "例如：中国建设银行";
  /// "开户支行："
  String get sbank => "开户支行：";
  /// "请输入开户支行"
  String get pleasesbank => "请输入开户支行";
  /// "提示：一旦设置成功，将无法修改，请您谨慎填写。"
  String get paynotice => "提示：一旦设置成功，将无法修改，请您谨慎填写。";
  /// "买家："
  String get selluser => "买家：";
  /// "卖家："
  String get sellllllluser => "卖家：";
  /// "交易手续费用"
  String get sellfee => "交易手续费用";
  /// "交易须知："
  String get sellneedknow => "交易须知：";
  /// "M0级别用户将无法出售MIGO。"
  String get sellneedknowinfo => "M0级别用户将无法出售MIGO。";
  /// "买家的支付方式："
  String get sellpaymethod => "买家的支付方式：";
  /// "订单已完成支付"
  String get sellpaid => "订单已完成支付";
  /// "创建订单"
  String get sellcreate => "创建订单";
  /// "完成支付"
  String get sellorderpaid => "完成支付";
  /// "买家付款"
  String get sellmakesure => "买家付款";
  /// "卖家放币"
  String get sellmakesurecoin => "卖家放币";
  /// "买家确认"
  String get sellsure => "买家确认";
  /// "订单完成"
  String get sellfinish => "订单完成";
  /// "购买量"
  String get buynumber => "购买量";
  /// "需付"
  String get buyamout => "需付";
  /// "出售量"
  String get sellnumber => "出售量";
  /// "收款"
  String get sellamount => "收款";
  /// "等待买家付款"
  String get sellwaitpay => "等待买家付款";
  /// "收款人手机号："
  String get payusermobile => "收款人手机号：";
  /// "已收款,确认放行"
  String get sellsellcoin => "已收款,确认放行";
  /// "付款信息(任选一种)"
  String get alertpaynotice => "付款信息(任选一种)";
  /// "收款人信息"
  String get alertuserinfo => "收款人信息";
  /// "扣除MIGO总量"
  String get selltotalnumber => "扣除MIGO总量";
  /// "交易单价"
  String get sellsingleprice => "交易单价";
  /// "交易总价"
  String get selltotalprice => "交易总价";
  /// "银行卡支付"
  String get bankpay => "银行卡支付";
  /// "银行卡号："
  String get banknumber => "银行卡号：";
  /// "开户支行："
  String get bankbranch => "开户支行：";
  /// "交易规则"
  String get rule => "交易规则";
  /// "请及时联系客服协助"
  String get servicehelp => "请及时联系客服协助";
  /// "卖家付款信息不吻合，交易取消"
  String get notrealname => "卖家付款信息不吻合，交易取消";
  /// "提交申诉"
  String get submitapply => "提交申诉";
  /// "您当前正在进行申诉，一旦申诉成功，对方账号将会进入冻结状态。请小心操作，恶意申诉者，核实后将被系统冻结"
  String get submitapplynotice => "您当前正在进行申诉，一旦申诉成功，对方账号将会进入冻结状态。请小心操作，恶意申诉者，核实后将被系统冻结";
  /// "未付全款，恢复订单"
  String get notpayall => "未付全款，恢复订单";
  /// "支付宝支付"
  String get alipaypay => "支付宝支付";
  /// "支付宝账号："
  String get alipayaccount => "支付宝账号：";
  /// "TRC20支付"
  String get trcpay => "TRC20支付";
  /// "如果收款人还没发放MIGO币给你，请联系以上号码"
  String get notpaycoin => "如果收款人还没发放MIGO币给你，请联系以上号码";
  /// "未实名"
  String get notauth => "未实名";
}

class _I18n_zh_CN extends I18n {
  const _I18n_zh_CN();

  @override
  TextDirection get textDirection => TextDirection.ltr;
}

class _I18n_en_US extends I18n {
  const _I18n_en_US();

  /// "Hello ${name}"
  @override
  String greetTo(String name) => "Hello ${name}";
  /// "Sign in"
  @override
  String get login => "Sign in";
  /// "Sign out"
  @override
  String get loginout => "Sign out";
  /// "English"
  @override
  String get language => "English";
  /// "Language"
  @override
  String get lang => "Language";
  /// "Home"
  @override
  String get home => "Home";
  /// "Exchange"
  @override
  String get exchange => "Exchange";
  /// "Market"
  @override
  String get market => "Market";
  /// "Mine"
  @override
  String get mine => "Mine";
  /// "My backpackage"
  @override
  String get mypackage => "My backpackage";
  /// "Recharge"
  @override
  String get recharge => "Recharge";
  /// "Withdraw"
  @override
  String get withdraw => "Withdraw";
  /// "Withdrawal address:"
  @override
  String get withdrawaddress => "Withdrawal address:";
  /// "Withdraw quantity:"
  @override
  String get withdrawnum => "Withdraw quantity:";
  /// "Withdrawal notes:"
  @override
  String get withdrawrule => "Withdrawal notes:";
  /// "Withdraw success"
  @override
  String get withdrawsuccess => "Withdraw success";
  /// "Arrival quantity:"
  @override
  String get arrivalquantity => "Arrival quantity:";
  /// "Team"
  @override
  String get team => "Team";
  /// "Daily income"
  @override
  String get dayincome => "Daily income";
  /// "My Team"
  @override
  String get myteam => "My Team";
  /// "My earnings"
  @override
  String get myearn => "My earnings";
  /// "Invite friends"
  @override
  String get invite => "Invite friends";
  /// "Appeal"
  @override
  String get shensu => "Appeal";
  /// "Buy not paid, transaction canceled"
  @override
  String get buynotpay => "Buy not paid, transaction canceled";
  /// "The buyer has paid, confirm the currency release"
  @override
  String get buypaiad => "The buyer has paid, confirm the currency release";
  /// "I have paid and the seller has not released the currency"
  @override
  String get sellnotpaycoin => "I have paid and the seller has not released the currency";
  /// "self-unblocking"
  @override
  String get autoaccount => "self-unblocking";
  /// "Your account transaction is regulated and there is no bad record, please keep it!"
  @override
  String get accountright => "Your account transaction is regulated and there is no bad record, please keep it!";
  /// "Unlock account"
  @override
  String get unlockaccount => "Unlock account";
  /// "Commissioned"
  @override
  String get weituo => "Commissioned";
  /// "Password"
  @override
  String get password => "Password";
  /// "Please fill in the name on the ID"
  @override
  String get pleaseinputname => "Please fill in the name on the ID";
  /// "Please fill in the ID number"
  @override
  String get pleaseinputid => "Please fill in the ID number";
  /// "Please enter your mobile phone number bound to your bank card"
  @override
  String get pleaseinputbanknumber => "Please enter your mobile phone number bound to your bank card";
  /// "Name"
  @override
  String get name => "Name";
  /// "Type of certificate"
  @override
  String get idtype => "Type of certificate";
  /// "ID number"
  @override
  String get idnumber => "ID number";
  /// "Driver license"
  @override
  String get iddrive => "Driver license";
  /// "Passport"
  @override
  String get idprotect => "Passport";
  /// "ID card"
  @override
  String get idcard => "ID card";
  /// "Mobile"
  @override
  String get phone => "Mobile";
  /// "Email"
  @override
  String get email => "Email";
  /// "Congratulations"
  @override
  String get congratulations => "Congratulations";
  /// "Phone number"
  @override
  String get pleaseinputphone => "Phone number";
  /// "Email"
  @override
  String get pleaseinputemail => "Email";
  /// "Password"
  @override
  String get pleaseinputpwd => "Password";
  /// "Enter transaction password"
  @override
  String get pleasetxpassword => "Enter transaction password";
  /// "Verification code"
  @override
  String get verificationcode => "Verification code";
  /// "New password"
  @override
  String get pleaseinputnewpwd => "New password";
  /// "Confirm password"
  @override
  String get confirminputnewpwd => "Confirm password";
  /// "Confirm and Sign in"
  @override
  String get confirmlogin => "Confirm and Sign in";
  /// "Verification code"
  @override
  String get getcoude => "Verification code";
  /// "Reacquire"
  @override
  String get reacquire => "Reacquire";
  /// "Successful redemption"
  @override
  String get exchagesuccess => "Successful redemption";
  /// "Setting"
  @override
  String get setting => "Setting";
  /// "Security center"
  @override
  String get safecenter => "Security center";
  /// "Feedback"
  @override
  String get feedback => "Feedback";
  /// "About"
  @override
  String get about => "About";
  /// "Quantity"
  @override
  String get number => "Quantity";
  /// "Date"
  @override
  String get date => "Date";
  /// "Time"
  @override
  String get time => "Time";
  /// "Total"
  @override
  String get total => "Total";
  /// "Done"
  @override
  String get finish => "Done";
  /// "Verified"
  @override
  String get verified => "Verified";
  /// "Current binding"
  @override
  String get currentbinding => "Current binding";
  /// "Login password"
  @override
  String get loginpwd => "Login password";
  /// "Transaction password"
  @override
  String get txpassword => "Transaction password";
  /// "Save"
  @override
  String get save => "Save";
  /// "Golden shovel"
  @override
  String get shovel_gold => "Golden shovel";
  /// "Sliver shovel"
  @override
  String get shovel_sliver => "Sliver shovel";
  /// "Copper shovel"
  @override
  String get shovel_iron => "Copper shovel";
  /// "Novice"
  @override
  String get newer => "Novice";
  /// "Go to backpack"
  @override
  String get gotopackage => "Go to backpack";
  /// "Invitation record"
  @override
  String get inviterecord => "Invitation record";
  /// "Available balance"
  @override
  String get availablebalance => "Available balance";
  /// "Asset account"
  @override
  String get assetaccount => "Asset account";
  /// "Share"
  @override
  String get teamgroupshare => "Share";
  /// "Leadership"
  @override
  String get teamgroupleader => "Leadership";
  /// "Direct push"
  @override
  String get teamgrouppush => "Direct push";
  /// "Output"
  @override
  String get output => "Output";
  /// "Estimate"
  @override
  String get estimate => "Estimate";
  /// "Yesterday's team earnings"
  @override
  String get lasetteamvalue => "Yesterday's team earnings";
  /// "Total revenue"
  @override
  String get totalteamvalue => "Total revenue";
  /// "Build team of mines\nParticipate pool dividends"
  @override
  String get totalnotice => "Build team of mines\nParticipate pool dividends";
  /// "Participate"
  @override
  String get teamjoin => "Participate";
  /// "Daily static of community"
  @override
  String get teamstaticvalue => "Daily static of community";
  /// "Balance"
  @override
  String get balance => "Balance";
  /// "Currency"
  @override
  String get choosecoin => "Currency";
  /// "Price"
  @override
  String get price => "Price";
  /// "Fee reduction"
  @override
  String get feereduction => "Fee reduction";
  /// "Fee"
  @override
  String get feereduction2 => "Fee";
  /// "Current level ${level}"
  @override
  String currlevel(String level) => "Current level ${level}";
  /// "Next level ${level}"
  @override
  String nextlevel(String level) => "Next level ${level}";
  /// "Currently purchasing package"
  @override
  String get currbuy => "Currently purchasing package";
  /// "Redeem now"
  @override
  String get redeemnow => "Redeem now";
  /// "Confirm redemption"
  @override
  String get confirmexchange => "Confirm redemption";
  /// "Supply"
  @override
  String get supply => "Supply";
  /// "Least get"
  @override
  String get leastget => "Least get";
  /// "Price slippage"
  @override
  String get priceslippage => "Price slippage";
  /// "Handling fee"
  @override
  String get handlingfee => "Handling fee";
  /// "Buy ${e} package"
  @override
  String buy(String e) => "Buy ${e} package";
  /// "Error account or password"
  @override
  String get erroraccount => "Error account or password";
  /// "Forget password?"
  @override
  String get forgetpwd => "Forget password?";
  /// "Sign up"
  @override
  String get register => "Sign up";
  /// "Next"
  @override
  String get next => "Next";
  /// "Confirm"
  @override
  String get sure => "Confirm";
  /// "Cancel"
  @override
  String get cancel => "Cancel";
  /// "Are you sure you want to log out?"
  @override
  String get canyouexit => "Are you sure you want to log out?";
  /// "Scan the QR code to recharge"
  @override
  String get scanqrtorecharge => "Scan the QR code to recharge";
  /// "Recharge address (copy address)"
  @override
  String get copyaddress => "Recharge address (copy address)";
  /// "Hour"
  @override
  String get hour => "Hour";
  /// "APP upgrade notice"
  @override
  String get upnotice => "APP upgrade notice";
  /// "press again to exit"
  @override
  String get againexit => "press again to exit";
  /// "1. The minimum recharge amount: ${e} USDT, less than this amount will not be credited to the account and cannot be returned."
  @override
  String notice1(String e) => "1. The minimum recharge amount: ${e} USDT, less than this amount will not be credited to the account and cannot be returned.";
  /// "1. This address only accepts ${e} assets, sending other currencies to this address will not be able to retrieve them."
  @override
  String notice2(String e) => "1. This address only accepts ${e} assets, sending other currencies to this address will not be able to retrieve them.";
  /// "2. Recharge to the wallet balance by default."
  @override
  String get notice3 => "2. Recharge to the wallet balance by default.";
  /// "3. Your recharge address will not change frequently, you can recharge; if there is any change, we will try our best to notify you via website announcement or email."
  @override
  String get notice4 => "3. Your recharge address will not change frequently, you can recharge; if there is any change, we will try our best to notify you via website announcement or email.";
  /// "Please enter or long press to paste"
  @override
  String get pleaseinputorcopy => "Please enter or long press to paste";
  /// "Please enter the quantity"
  @override
  String get pleaseinputonumber => "Please enter the quantity";
  /// "Available amount:"
  @override
  String get availableamount => "Available amount:";
  /// "Actual arrival:"
  @override
  String get actualarrival => "Actual arrival:";
  /// "Earn"
  @override
  String get homeearn => "Earn";
  /// "Mortgage"
  @override
  String get mortgage => "Mortgage";
  /// "Payment required"
  @override
  String get homepay => "Payment required";
  /// "Daily output"
  @override
  String get dailyoutput => "Daily output";
  /// "Mining cycle"
  @override
  String get miningcycle => "Mining cycle";
  /// "Mining amount"
  @override
  String get miningamount => "Mining amount";
  /// "Add other methods"
  @override
  String get addother => "Add other methods";
  /// "Please add a payment method"
  @override
  String get addpaymethod => "Please add a payment method";
  /// "Please choose a payment method"
  @override
  String get pleaseaddpay => "Please choose a payment method";
  /// "Daily output"
  @override
  String get miningoutput => "Daily output";
  /// "Total output"
  @override
  String get miningtotaloutput => "Total output";
  /// "Obtain"
  @override
  String get obtain => "Obtain";
  /// "Mine now"
  @override
  String get minenow => "Mine now";
  /// "Used"
  @override
  String get homeused => "Used";
  /// "Payment record"
  @override
  String get miningpaymentrecord => "Payment record";
  /// "Revenue record"
  @override
  String get miningrevenuerecord => "Revenue record";
  /// "Team revenue record"
  @override
  String get teamearnrecord => "Team revenue record";
  /// "Pay"
  @override
  String get pay => "Pay";
  /// "Sharing rewards"
  @override
  String get sharerewards => "Sharing rewards";
  /// "Current title"
  @override
  String get currtitle => "Current title";
  /// "Cumulative pledged mining"
  @override
  String get cumulativepledgedmining => "Cumulative pledged mining";
  /// "Compliance level"
  @override
  String get compliancelevel => "Compliance level";
  /// "See Point Reward"
  @override
  String get seePoint => "See Point Reward";
  /// "Shovel in use"
  @override
  String get shovelinuse => "Shovel in use";
  /// "Days"
  @override
  String get day => "Days";
  /// "Verified"
  @override
  String get inviteverified => "Verified";
  /// "Not Verified"
  @override
  String get notinviteverified => "Not Verified";
  /// "All"
  @override
  String get all => "All";
  /// "generation"
  @override
  String get generation => "generation";
  /// "Every active user"
  @override
  String get everyactiveuser => "Every active user";
  /// "Reward"
  @override
  String get reward => "Reward";
  /// "Enjoy"
  @override
  String get enjoy => "Enjoy";
  /// "My level"
  @override
  String get currentlevel => "My level";
  /// "Mining pool dividend"
  @override
  String get minedividends => "Mining pool dividend";
  /// "My community"
  @override
  String get mycommunity => "My community";
  /// "People certified"
  @override
  String get numberpeople => "People certified";
  /// "Total certified"
  @override
  String get totalnumberpeople => "Total certified";
  /// "Reset password"
  @override
  String get resetpwd => "Reset password";
  /// "${sender}"
  @override
  String space(String sender) => "${sender}";
  /// ""
  @override
  String get teamleadertotal => "";
  /// "Number of team"
  @override
  String get teamnumber => "Number of team";
  /// "Team Performance"
  @override
  String get teamperformance => "Team Performance";
  /// "Mining amount"
  @override
  String get dynamicincome => "Mining amount";
  /// "Direct Push Award"
  @override
  String get directPushAward => "Direct Push Award";
  /// "Reward for meeting standards"
  @override
  String get aimreward => "Reward for meeting standards";
  /// "My value"
  @override
  String get denomination => "My value";
  /// "Update"
  @override
  String get coinupdate => "Update";
  /// "History record"
  @override
  String get history => "History record";
  /// "Warm Reminder"
  @override
  String get notice => "Warm Reminder";
  /// "Upload ID photo"
  @override
  String get uploadid => "Upload ID photo";
  /// "Hold the front of the ID photo"
  @override
  String get idfront => "Hold the front of the ID photo";
  /// "Hold the back of the ID photo"
  @override
  String get idback => "Hold the back of the ID photo";
  /// "The withdrawal address is illegal, please re-enter"
  @override
  String get noticenotaddress => "The withdrawal address is illegal, please re-enter";
  /// "Take photo"
  @override
  String get takephoto => "Take photo";
  /// "Select from album"
  @override
  String get album => "Select from album";
  /// "Submit"
  @override
  String get submit => "Submit";
  /// "Change binding"
  @override
  String get changebind => "Change binding";
  /// "Current binding"
  @override
  String get currbind => "Current binding";
  /// "Binding rule: select one of mobile phone number and email to bind"
  @override
  String get bindrule => "Binding rule: select one of mobile phone number and email to bind";
  /// "Transfer Coupons"
  @override
  String get reeltitle => "Transfer Coupons";
  /// "Coupons"
  @override
  String get reelaction => "Coupons";
  /// "Transfer to user:"
  @override
  String get coupontouser => "Transfer to user:";
  /// "Transfer amount:"
  @override
  String get coupontousercount => "Transfer amount:";
  /// "Verify User"
  @override
  String get reelverified => "Verify User";
  /// "Please verify the user first"
  @override
  String get pleasereelverified => "Please verify the user first";
  /// "Max${e}"
  @override
  String reelmaxcount(String e) => "Max${e}";
  /// "Add one more"
  @override
  String get addone => "Add one more";
  /// "Sorry, the user ID you entered has not been registered and cannot be added"
  @override
  String get reelerror => "Sorry, the user ID you entered has not been registered and cannot be added";
  /// "Congratulations, this ID is a registered ID"
  @override
  String get reelsuccess => "Congratulations, this ID is a registered ID";
  /// "Current Total Productivity"
  @override
  String get currtotalproduce => "Current Total Productivity";
  /// "Backpack Capacity"
  @override
  String get packagesize => "Backpack Capacity";
  /// "Today's estimate obtained"
  @override
  String get todaypreget => "Today's estimate obtained";
  /// "Cumulative output"
  @override
  String get totalgetmigos => "Cumulative output";
  /// "specification"
  @override
  String get specification => "specification";
  /// "Durability"
  @override
  String get durability => "Durability";
  /// "Production Volume"
  @override
  String get production => "Production Volume";
  /// "Volume"
  @override
  String get volume => "Volume";
  /// "Use"
  @override
  String get use => "Use";
  /// "Are you sure you want to use this item?"
  @override
  String get usernotice => "Are you sure you want to use this item?";
  /// "1. Type of document: ID card, passport or driver’s license.\n2. The document information and face must be clearly seen, and the document must be hand-held to take pictures.\n3. The document must not exceed 500kb.\n4. The content of the photo is true and valid, No modification is allowed.\n5. The uploaded file formats are pdf, jpg, jpeg and png."
  @override
  String get uploadnotice => "1. Type of document: ID card, passport or driver’s license.\n2. The document information and face must be clearly seen, and the document must be hand-held to take pictures.\n3. The document must not exceed 500kb.\n4. The content of the photo is true and valid, No modification is allowed.\n5. The uploaded file formats are pdf, jpg, jpeg and png.";
  /// "The name and ID number cannot be changed after the first submission. In order to avoid filling in false information, the recharge and withdrawal cannot be approved, please fill in the real information carefully."
  @override
  String get authnotice => "The name and ID number cannot be changed after the first submission. In order to avoid filling in false information, the recharge and withdrawal cannot be approved, please fill in the real information carefully.";
  /// "Invitation code: "
  @override
  String get myinvitecode => "Invitation code: ";
  /// "Invite 10 friends and complete real-name authentication \n to get a blind box"
  @override
  String get myinvitecodenotice => "Invite 10 friends and complete real-name authentication \n to get a blind box";
  /// "Invite Link"
  @override
  String get invitelink => "Invite Link";
  /// "Save Poster"
  @override
  String get saveimage => "Save Poster";
  /// "people in total"
  @override
  String get peopleintotal => "people in total";
  /// "Successed"
  @override
  String get success => "Successed";
  /// "Earnings Record"
  @override
  String get earnrecord => "Earnings Record";
  /// "1. Withdrawal will deduct part of the handling fee, which is based on the actual arrival."
  @override
  String get withDrawNotice => "1. Withdrawal will deduct part of the handling fee, which is based on the actual arrival.";
  /// "User Agreement"
  @override
  String get settinguserprotocol => "User Agreement";
  /// "Privacy Agreement"
  @override
  String get settingprotocol => "Privacy Agreement";
  /// "APP version update content"
  @override
  String get settingupdate => "APP version update content";
  /// "APP version"
  @override
  String get appcurrversion => "APP version";
  /// "Friend invitation process"
  @override
  String get feedinvite => "Friend invitation process";
  /// "Account management matters"
  @override
  String get feedaccount => "Account management matters";
  /// "Explanation of mine income"
  @override
  String get feedmines => "Explanation of mine income";
  /// "Use of other functions"
  @override
  String get feeduse => "Use of other functions";
  /// "Actual payment amount"
  @override
  String get realpayamount => "Actual payment amount";
  /// "Current purchase amount"
  @override
  String get realpayamount2 => "Current purchase amount";
  /// "Send feedback"
  @override
  String get feed => "Send feedback";
  /// "Withdrawal of funds and account deletion process"
  @override
  String get feeddel => "Withdrawal of funds and account deletion process";
  /// "Please briefly describe your question or comment so that we can provide you with better help."
  @override
  String get feennotice => "Please briefly describe your question or comment so that we can provide you with better help.";
  /// "Select file"
  @override
  String get feedchoose => "Select file";
  /// "Please input content"
  @override
  String get pleaseinput => "Please input content";
  /// "Using"
  @override
  String get using => "Using";
  /// "shovel"
  @override
  String get shovel => "shovel";
  /// "Pending deal"
  @override
  String get waitbuy => "Pending deal";
  /// "Transactioning"
  @override
  String get buying => "Transactioning";
  /// "Click to modify payment information"
  @override
  String get modpay => "Click to modify payment information";
  /// "Paid"
  @override
  String get paid => "Paid";
  /// "Total amount of global mining pool dividends"
  @override
  String get mineaddgrade => "Total amount of global mining pool dividends";
  /// "Today's global mining pool dividends"
  @override
  String get minetodayaddgrade => "Today's global mining pool dividends";
  /// "Global mining pool dividend total"
  @override
  String get minetotaladdgrade => "Global mining pool dividend total";
  /// "Start and end date"
  @override
  String get startdate => "Start and end date";
  /// "Dividend Date"
  @override
  String get getmoneydate => "Dividend Date";
  /// "Team Overview"
  @override
  String get teamdetail => "Team Overview";
  /// "Direct Push"
  @override
  String get minepush => "Direct Push";
  /// "Under umbrella"
  @override
  String get mineumbrella => "Under umbrella";
  /// "My direct push number"
  @override
  String get minepushanumber => "My direct push number";
  /// "My umbrella number"
  @override
  String get mineumbrellanumber => "My umbrella number";
  /// "Add pledge this week"
  @override
  String get weakaddMEGO => "Add pledge this week";
  /// "Cumulative pledge"
  @override
  String get allmego => "Cumulative pledge";
  /// "Global Mining Pool Dividend"
  @override
  String get earthmoney => "Global Mining Pool Dividend";
  /// "Number of effective users"
  @override
  String get realuser => "Number of effective users";
  /// "Bank Card Number"
  @override
  String get bankNo => "Bank Card Number";
  /// "Please enter the correct bank card number"
  @override
  String get pleasebankNo => "Please enter the correct bank card number";
  /// "Please enter the unit price"
  @override
  String get pleaseprice => "Please enter the unit price";
  /// "Transaction fee level"
  @override
  String get selllevel => "Transaction fee level";
  /// "Pending Authentication"
  @override
  String get auth0 => "Pending Authentication";
  /// "Under review"
  @override
  String get auth1 => "Under review";
  /// "Approved by"
  @override
  String get auth2 => "Approved by";
  /// "Audit rejected"
  @override
  String get auth3 => "Audit rejected";
  /// "Chinese domestic users"
  @override
  String get curruser => "Chinese domestic users";
  /// "Overseas users"
  @override
  String get otheruser => "Overseas users";
  /// "Deposit and withdrawal history"
  @override
  String get rechargerecord => "Deposit and withdrawal history";
  /// "Withdrawal Record"
  @override
  String get relfectrecord => "Withdrawal Record";
  /// "Pending review"
  @override
  String get coinStatus0 => "Pending review";
  /// "Transferring"
  @override
  String get coinStatus1 => "Transferring";
  /// "Confirming"
  @override
  String get coinStatus2 => "Confirming";
  /// "Transfer Successful"
  @override
  String get coinStatus3 => "Transfer Successful";
  /// "Approval denied"
  @override
  String get coinStatus4 => "Approval denied";
  /// "Transfer failed"
  @override
  String get coinStatus5 => "Transfer failed";
  /// "Sending transaction"
  @override
  String get coinStatus6 => "Sending transaction";
  /// "Packaging"
  @override
  String get coinStatus7 => "Packaging";
  /// "Exchange History"
  @override
  String get exchangehistory => "Exchange History";
  /// "Enough"
  @override
  String get enough => "Enough";
  /// "Finished"
  @override
  String get alfinish => "Finished";
  /// " ERC20 is not currently supported"
  @override
  String get rechargeNotsupport => " ERC20 is not currently supported";
  /// "Arrival amount"
  @override
  String get realnum => "Arrival amount";
  /// "Remarks"
  @override
  String get remark => "Remarks";
  /// "Aim"
  @override
  String get arriveAim => "Aim";
  /// "Getted"
  @override
  String get geted => "Getted";
  /// "Deposit and withdrawal order"
  @override
  String get rechagerecordorder => "Deposit and withdrawal order";
  /// "Daily income"
  @override
  String get yearterdayoutput => "Daily income";
  /// "Please enter a 6-digit password"
  @override
  String get pleasesixpwd => "Please enter a 6-digit password";
  /// "Minimum withdrawal${e}"
  @override
  String pleasemincoinnumber(String e) => "Minimum withdrawal${e}";
  /// "Please enter the number greater than ${e}"
  @override
  String noticemincoimnumber(String e) => "Please enter the number greater than ${e}";
  /// "Please enter a 6-12 digit letter combination password"
  @override
  String get pleasesixto12pwd => "Please enter a 6-12 digit letter combination password";
  /// "You have entered the wrong password 5 times, please change the new password"
  @override
  String get pleasereinputnew => "You have entered the wrong password 5 times, please change the new password";
  /// "It is detected that you have not set your own trading password, please go to the setting immediately"
  @override
  String get nottxpwd => "It is detected that you have not set your own trading password, please go to the setting immediately";
  /// "1) Your name and ID number cannot be changed after authentication. In order to avoid filling in false information and failing to approve the recharge and withdrawal, please fill in your real information carefully.\n2) Please fill in your binding information The mobile phone number of the bank card.\n3) Please wait patiently, because the verification process takes time."
  @override
  String get threeauthNotice => "1) Your name and ID number cannot be changed after authentication. In order to avoid filling in false information and failing to approve the recharge and withdrawal, please fill in your real information carefully.\n2) Please fill in your binding information The mobile phone number of the bank card.\n3) Please wait patiently, because the verification process takes time.";
  /// "1) Your name and ID number cannot be changed after authentication. In order to avoid filling in false information and failing to approve the recharge and withdrawal, please fill in your real information carefully.\n2) Please click Next Hold the ID photo and take a photo, you need to clearly see your face, the information before and after the ID. In addition, you need to prepare a small note, clearly write your own MIGO invitation code, if not Yes, the customer service has the right to refuse the audit and certification.\n3) Please be patient, because the audit and certification process takes time to process. (Overseas users will take longer)"
  @override
  String get threeauthNotice2 => "1) Your name and ID number cannot be changed after authentication. In order to avoid filling in false information and failing to approve the recharge and withdrawal, please fill in your real information carefully.\n2) Please click Next Hold the ID photo and take a photo, you need to clearly see your face, the information before and after the ID. In addition, you need to prepare a small note, clearly write your own MIGO invitation code, if not Yes, the customer service has the right to refuse the audit and certification.\n3) Please be patient, because the audit and certification process takes time to process. (Overseas users will take longer)";
  /// "1. The minimum withdrawal amount is ${e}.\n2. A portion of the handling fee will be deducted for withdrawals, which are based on the actual receipt.\n3. The actual receipt amount will be subject to a certain review and judgment. The withdrawal limit is the benchmark.\n4. To ensure the safety of your funds, when you change your password or other security-related personal information, we will conduct a manual review of the withdrawal."
  @override
  String withdrawnoticerule(String e) => "1. The minimum withdrawal amount is ${e}.\n2. A portion of the handling fee will be deducted for withdrawals, which are based on the actual receipt.\n3. The actual receipt amount will be subject to a certain review and judgment. The withdrawal limit is the benchmark.\n4. To ensure the safety of your funds, when you change your password or other security-related personal information, we will conduct a manual review of the withdrawal.";
  /// "Passwords are not consistent"
  @override
  String get notsamepwd => "Passwords are not consistent";
  /// "Need to know when transferring certification volume:"
  @override
  String get reealnotice => "Need to know when transferring certification volume:";
  /// "1. The minimum increase unit is 1."
  @override
  String get reealnotice1 => "1. The minimum increase unit is 1.";
  /// "2. You can add up to five users at once."
  @override
  String get reealnotice2 => "2. You can add up to five users at once.";
  /// "3. Please verify the user ID you entered first, and confirm that it is a registered user before adding it."
  @override
  String get reealnotice3 => "3. Please verify the user ID you entered first, and confirm that it is a registered user before adding it.";
  /// "4. Click the icon in the upper right corner to view your certification voucher transfer record."
  @override
  String get reealnotice4 => "4. Click the icon in the upper right corner to view your certification voucher transfer record.";
  /// "Reel Record"
  @override
  String get reelrecord => "Reel Record";
  /// "Real-name authentication volume transfer to increase record"
  @override
  String get reelrecordhead => "Real-name authentication volume transfer to increase record";
  /// "Real-name authentication volume"
  @override
  String get reelusename => "Real-name authentication volume";
  /// "You currently have ${e} certificates available, are you sure to use it?"
  @override
  String reelusecontent(String e) => "You currently have ${e} certificates available, are you sure to use it?";
  /// "An authentication volume has been consumed! Please wait patiently for the authentication result"
  @override
  String get reeluserd => "An authentication volume has been consumed! Please wait patiently for the authentication result";
  /// "You currently do not have any available certification volume,\nplease ask your inviter or superior to get it!"
  @override
  String get reelnouse => "You currently do not have any available certification volume,\nplease ask your inviter or superior to get it!";
  /// "Please enter your phone number or email"
  @override
  String get pleaseinputuserid => "Please enter your phone number or email";
  /// "Please enter the number: the minimum is 1"
  @override
  String get pleaseinputreelnumber => "Please enter the number: the minimum is 1";
  /// "The number of transfer users reaches the upper limit"
  @override
  String get reelnumbertomax => "The number of transfer users reaches the upper limit";
  /// "Reel has been successfully transferred"
  @override
  String get reelrequestSuccess => "Reel has been successfully transferred";
  /// "Current certification volume number:"
  @override
  String get reelrequestcurrnumber => "Current certification volume number:";
  /// "Cannot transfer to the same account"
  @override
  String get notsameaccount => "Cannot transfer to the same account";
  /// "The number of certification coupons is insufficient, please modify the number"
  @override
  String get reelnumbertonotenough => "The number of certification coupons is insufficient, please modify the number";
  /// "Please enter a 6-digit transaction password"
  @override
  String get pleasesixtxpwd => "Please enter a 6-digit transaction password";
  /// "Exchange Rate"
  @override
  String get huilv => "Exchange Rate";
  /// "Transferred"
  @override
  String get reelstatus1 => "Transferred";
  /// "This area is not yet open"
  @override
  String get notopen => "This area is not yet open";
  /// "Pledged Mining Total"
  @override
  String get teamminetotal => "Pledged Mining Total";
  /// "Reloaded"
  @override
  String get reelstatus2 => "Reloaded";
  /// "Used"
  @override
  String get reelstatus3 => "Used";
  /// "Returned"
  @override
  String get reelstatus4 => "Returned";
  /// "Global Dividend"
  @override
  String get globlalmoney => "Global Dividend";
  /// "Team Rewards"
  @override
  String get teammoney => "Team Rewards";
  /// "Reposted"
  @override
  String get reeledfinish => "Reposted";
  /// "Total pledged mining"
  @override
  String get teamtotaltotal => "Total pledged mining";
  /// "Community mining"
  @override
  String get teamtotalmin => "Community mining";
  /// "Prompt\nPlease go to the security center to bind your mobile number before December 18, otherwise you will not be able to log in"
  @override
  String get cannoteamil => "Prompt\nPlease go to the security center to bind your mobile number before December 18, otherwise you will not be able to log in";
  /// "Generation ${e}"
  @override
  String secondegenra(String e) => "Generation ${e}";
  /// "Real-named"
  @override
  String get auth => "Real-named";
  /// "Overseas manual authentication"
  @override
  String get authother => "Overseas manual authentication";
  /// "Exchange"
  @override
  String get coinexchange => "Exchange";
  /// "Look forward to it"
  @override
  String get notopen2 => "Look forward to it";
  /// "Opening soon"
  @override
  String get notopen3 => "Opening soon";
  /// "Today's price"
  @override
  String get extodayprice => "Today's price";
  /// "Today's Price"
  @override
  String get extodaypricecny => "Today's Price";
  /// "Yesterday Price"
  @override
  String get exyesterdayprice => "Yesterday Price";
  /// "Increase"
  @override
  String get exupdown => "Increase";
  /// "Today's Transaction Volume"
  @override
  String get extodaycount => "Today's Transaction Volume";
  /// "Platform transaction volume"
  @override
  String get explatformcount => "Platform transaction volume";
  /// "Available balance"
  @override
  String get exablebanence => "Available balance";
  /// "Buy"
  @override
  String get exbuy => "Buy";
  /// "Current Purchase List"
  @override
  String get exbuylist => "Current Purchase List";
  /// "Order Number"
  @override
  String get exorderno => "Order Number";
  /// "Quantity"
  @override
  String get exordernoNum => "Quantity";
  /// "Price"
  @override
  String get exsingleprice => "Price";
  /// "Amount"
  @override
  String get expreamount => "Amount";
  /// "Sell Now"
  @override
  String get exsellnow => "Sell Now";
  /// "Finished"
  @override
  String get finished => "Finished";
  /// "Post Buy"
  @override
  String get expostbuy => "Post Buy";
  /// "Amount"
  @override
  String get exposetnumber => "Amount";
  /// "Please enter the purchase amount"
  @override
  String get expostplease => "Please enter the purchase amount";
  /// "Synchronization Price"
  @override
  String get expostasync => "Synchronization Price";
  /// "Custom Price"
  @override
  String get expostself => "Custom Price";
  /// "price increase ratio"
  @override
  String get expostbili => "price increase ratio";
  /// "Payment Method"
  @override
  String get expostpaymethod => "Payment Method";
  /// "WeChat"
  @override
  String get paywx => "WeChat";
  /// "Alipay"
  @override
  String get payalipay => "Alipay";
  /// "Bank Card"
  @override
  String get paybank => "Bank Card";
  /// "Confirm Post"
  @override
  String get expostsend => "Confirm Post";
  /// "Total Price"
  @override
  String get totalprice => "Total Price";
  /// "Transaction time"
  @override
  String get subtime => "Transaction time";
  /// "Pending Payment"
  @override
  String get rnotpay => "Pending Payment";
  /// "To be confirmed"
  @override
  String get rnotsure => "To be confirmed";
  /// "Finished"
  @override
  String get rfinish => "Finished";
  /// "Revoked"
  @override
  String get rnotfinish => "Revoked";
  /// "Trade Order"
  @override
  String get rtitle => "Trade Order";
  /// "Sale"
  @override
  String get rsell => "Sale";
  /// "Confirm paid"
  @override
  String get rsurepay => "Confirm paid";
  /// "Waiting for the other party to release coins"
  @override
  String get rsurepaycoin => "Waiting for the other party to release coins";
  /// "Payment Information"
  @override
  String get rpayinfo => "Payment Information";
  /// "Payment Method"
  @override
  String get spaysetting => "Payment Method";
  /// "Buy"
  @override
  String get rbuy => "Buy";
  /// "I bought it"
  @override
  String get rbuytitle => "I bought it";
  /// "I sold it"
  @override
  String get rselltitle => "I sold it";
  /// "Payee Name:"
  @override
  String get susername => "Payee Name:";
  /// "Please enter the payee name"
  @override
  String get susernameplease => "Please enter the payee name";
  /// "For example: Alipay name/bank card/TRC20 wallet holder name"
  @override
  String get snameeg => "For example: Alipay name/bank card/TRC20 wallet holder name";
  /// "Receiving account number:"
  @override
  String get saccount => "Receiving account number:";
  /// "Payment address:"
  @override
  String get saccountaddress => "Payment address:";
  /// "Please enter the receiving account"
  @override
  String get saccountplease => "Please enter the receiving account";
  /// "For example: Alipay mobile phone number/bank card number/TRC20 wallet address"
  @override
  String get saccounteg => "For example: Alipay mobile phone number/bank card number/TRC20 wallet address";
  /// "Account Bank:"
  @override
  String get bankename => "Account Bank:";
  /// "Please enter the bank that opened the account"
  @override
  String get pleasebankname => "Please enter the bank that opened the account";
  /// "For example: China Construction Bank"
  @override
  String get bandeg => "For example: China Construction Bank";
  /// "Account opening branch:"
  @override
  String get sbank => "Account opening branch:";
  /// "Please enter the account opening branch"
  @override
  String get pleasesbank => "Please enter the account opening branch";
  /// "Prompt: Once the setting is successful, it cannot be modified. Please fill in carefully."
  @override
  String get paynotice => "Prompt: Once the setting is successful, it cannot be modified. Please fill in carefully.";
  /// "Buyer:"
  @override
  String get selluser => "Buyer:";
  /// "Seller:"
  @override
  String get sellllllluser => "Seller:";
  /// "Transaction fees"
  @override
  String get sellfee => "Transaction fees";
  /// "Transaction Instructions:"
  @override
  String get sellneedknow => "Transaction Instructions:";
  /// "M0 users can`t sell MIGO."
  @override
  String get sellneedknowinfo => "M0 users can`t sell MIGO.";
  /// "Buyer's payment method:"
  @override
  String get sellpaymethod => "Buyer's payment method:";
  /// "The order has been paid for"
  @override
  String get sellpaid => "The order has been paid for";
  /// "Create Order"
  @override
  String get sellcreate => "Create Order";
  /// "Sellorderpaid"
  @override
  String get sellorderpaid => "Sellorderpaid";
  /// "Buyer pays"
  @override
  String get sellmakesure => "Buyer pays";
  /// "Makesurecoin"
  @override
  String get sellmakesurecoin => "Makesurecoin";
  /// "Buyer Confirmation"
  @override
  String get sellsure => "Buyer Confirmation";
  /// "Order completed"
  @override
  String get sellfinish => "Order completed";
  /// "Buy Number"
  @override
  String get buynumber => "Buy Number";
  /// "Payment required"
  @override
  String get buyamout => "Payment required";
  /// "sellnumber"
  @override
  String get sellnumber => "sellnumber";
  /// "Collection"
  @override
  String get sellamount => "Collection";
  /// "Waiting for buyer to pay"
  @override
  String get sellwaitpay => "Waiting for buyer to pay";
  /// "Payee's mobile phone number:"
  @override
  String get payusermobile => "Payee's mobile phone number:";
  /// "Received, confirm release"
  @override
  String get sellsellcoin => "Received, confirm release";
  /// "Payment information (choose one)"
  @override
  String get alertpaynotice => "Payment information (choose one)";
  /// "Payee Information"
  @override
  String get alertuserinfo => "Payee Information";
  /// "Deduct the total amount of MIGO"
  @override
  String get selltotalnumber => "Deduct the total amount of MIGO";
  /// "Unit price"
  @override
  String get sellsingleprice => "Unit price";
  /// "Total price"
  @override
  String get selltotalprice => "Total price";
  /// "Trading Rules"
  @override
  String get rule => "Trading Rules";
  /// "Please contact customer service for assistance in time"
  @override
  String get servicehelp => "Please contact customer service for assistance in time";
  /// "Payment info error, cancelled"
  @override
  String get notrealname => "Payment info error, cancelled";
  /// "Submit an Appeal"
  @override
  String get submitapply => "Submit an Appeal";
  /// "You are currently appealing. Once the appeal is successful, the other party's account will be frozen. Please be careful, malicious applicants will be frozen by the system after verification"
  @override
  String get submitapplynotice => "You are currently appealing. Once the appeal is successful, the other party's account will be frozen. Please be careful, malicious applicants will be frozen by the system after verification";
  /// "Unpaid full payment, resume order"
  @override
  String get notpayall => "Unpaid full payment, resume order";
  /// "Alipay Pay"
  @override
  String get alipaypay => "Alipay Pay";
  /// "Alipay account number:"
  @override
  String get alipayaccount => "Alipay account number:";
  /// "TRC20 payment"
  @override
  String get trcpay => "TRC20 payment";
  /// "If the payee has not issued MIGO coins to you, please contact the above number"
  @override
  String get notpaycoin => "If the payee has not issued MIGO coins to you, please contact the above number";
  /// "Not Real Name"
  @override
  String get notauth => "Not Real Name";

  @override
  TextDirection get textDirection => TextDirection.ltr;
}

class GeneratedLocalizationsDelegate extends LocalizationsDelegate<WidgetsLocalizations> {
  const GeneratedLocalizationsDelegate();
  List<Locale> get supportedLocales {
    return const <Locale>[
      Locale("zh", "CN"),
      Locale("en", "US")
    ];
  }

  LocaleResolutionCallback resolution({Locale fallback}) {
    return (Locale locale, Iterable<Locale> supported) {
      if (isSupported(locale)) {
        return locale;
      }
      final Locale fallbackLocale = fallback ?? supported.first;
      return fallbackLocale;
    };
  }

  @override
  Future<WidgetsLocalizations> load(Locale locale) {
    I18n._locale ??= locale;
    I18n._shouldReload = false;
    final String lang = I18n._locale != null ? I18n._locale.toString() : "";
    final String languageCode = I18n._locale != null ? I18n._locale.languageCode : "";
    if ("zh_CN" == lang) {
      return SynchronousFuture<WidgetsLocalizations>(const _I18n_zh_CN());
    }
    else if ("en_US" == lang) {
      return SynchronousFuture<WidgetsLocalizations>(const _I18n_en_US());
    }
    else if ("zh" == languageCode) {
      return SynchronousFuture<WidgetsLocalizations>(const _I18n_zh_CN());
    }
    else if ("en" == languageCode) {
      return SynchronousFuture<WidgetsLocalizations>(const _I18n_en_US());
    }

    return SynchronousFuture<WidgetsLocalizations>(const I18n());
  }

  @override
  bool isSupported(Locale locale) {
    for (var i = 0; i < supportedLocales.length && locale != null; i++) {
      final l = supportedLocales[i];
      if (l.languageCode == locale.languageCode) {
        return true;
      }
    }
    return false;
  }

  @override
  bool shouldReload(GeneratedLocalizationsDelegate old) => I18n._shouldReload;
}